global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 1m

# A list of scrape configurations.
scrape_configs:
  - job_name: grafana
    static_configs:
      - targets:
        - grafana:3000
  - job_name: prometheus
    static_configs:
      - targets:
        - prometheus:9090
  - job_name: cortex1
    static_configs:
      - targets:
        - cortex1:9009
  - job_name: cortex2
    static_configs:
      - targets:
        - cortex2:9009
    
  
# Settings related to the remote write feature.
remote_write:
  - url: "http://cortex1:9009/api/v1/push"

  